name: "Close stale issues"

on:
  schedule:
    - cron: 0 * * * *

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/stale@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'This issue is stale because it has been open with no activity. Remove the stale label to defer, add keep label to have stale to ignore it, comment to defer for a few days. For more see https://github.com/github/pe-actions-experience/blob/master/doc/ops-issues.md'
        days-before-stale: 21
        days-before-close: 7
        exempt-issue-label: keep
